#!/bin/bash
git config --global alias.ll 'log --oneline'
git config --global alias.p 'push'
git config --global alias.pf 'push --force'
git config --global alias.st 'status'
git config --global alias.ap 'add --patch'
git config --global alias.cm 'commit --message'
git config --global alias.gl 'config --global --list'
git config --global alias.sfp 'push --force-with-lease'
git config --global alias.csm 'commit --signoff --message'
git config --global alias.staged 'diff --cached'
git config --global alias.rbim 'rebase -i master'
